estagios/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.root, name='root'),
    path('index', views.index, name='index'),
    path('create', views.create, name='create'),
    path('read', views.read, name='read'),
    path('update', views.update, name='update'),
    path('confirm_update', views.confirm_update, name='confirm_update'),
    path('delete', views.delete, name='delete'),
]

estagios/estagios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

estagios/core/models.py
from django.db import models

class VagaModel(models.Model):
    titulo = models.CharField('Título da Vaga', max_length=150)
    empresa = models.CharField('Empresa', max_length=150)
    telefone = models.CharField('Telefone', max_length=20)

    def __str__(self):
        return self.titulo

estagios/core/forms.py
from django import forms
from django.core.exceptions import ValidationError


class VagaForm(forms.Form):
    titulo = forms.CharField(max_length=150)
    empresa = forms.CharField(max_length=150)
    telefone = forms.CharField(max_length=20)
        
    def clean_titulo(self):
        nome = self.cleaned_data['titulo']
        return nome.upper()

    def clean_empresa(self):
        empresa = self.cleaned_data['empresa']
        if len(empresa) < 3:
            raise ValidationError('Empresa precisa ter ao menos três caracteres')
        return empresa

    def clean_telefone(self):
        telefone = self.cleaned_data['telefone']
        if telefone.startswith('19'):
            return telefone
        raise ValidationError('DDD válido somente o 19')

estagios/core/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from core.models import VagaModel
from core.forms import VagaForm

def root(request):
    return HttpResponseRedirect(reverse('core:index'))

def index(request):
    if request.method == 'GET':
        return render(request, "index.html")
    return HttpResponseRedirect(reverse('core:index'))

def create(request):
    if request.method == 'POST':
        form = VagaForm(request.POST)
        if form.is_valid():
            VagaModel.objects.create(**form.cleaned_data)
            return HttpResponseRedirect(reverse('core:index'))
        contexto = {'form': form}
        return render(request, "cadastro.html", contexto)
    contexto = {'form': VagaForm()}
    return render(request, 'cadastro.html', contexto)

def read(request):
    if request.method == 'POST':
        id = request.POST.get('id', '')
        try:
            vaga = VagaModel.objects.get(pk=id)
            contexto = {'vaga': vaga}
        except ValueError:
            contexto = {}
        return render(request, "detalhes.html", contexto)
    contexto = {'vagas': VagaModel.objects.all()}
    return render(request, 'listar.html', contexto)

def update(request):
    if request.method == 'POST':
        id = request.POST.get('id', '')
        try:
            form = VagaForm(VagaModel.objects.get(pk=id).__dict__)
            contexto = {'form': form, 'pk':id}
        except ValueError:
            contexto = {}
        return render(request, "atualizar2.html", contexto)
    contexto = {'vagas': VagaModel.objects.all()}
    return render(request, 'atualizar.html', contexto)

def confirm_update(request):
    if request.method == 'POST':
        id = request.POST['id']
        instance = get_object_or_404(VagaModel, id=id)
        form = VagaForm(request.POST)
        if form.is_valid():
            instance.__dict__.update(**form.cleaned_data)
            instance.save()
            contexto = {'vagas': VagaModel.objects.all()}
            return render(request, 'atualizar.html', contexto)
        contexto = {'form': form, 'pk':id}
        return render(request, "atualizar2.html", contexto)
    return render(request, "index.html")

def delete(request):
    if request.method == 'POST':
        id = request.POST.get('id', '')
        try:
            VagaModel.objects.get(pk=id).delete()
        except:
            pass
        return render(request, "index.html")
    contexto = {'vagas': VagaModel.objects.all()}
    return render(request, 'remover.html', contexto)

estagios/core/templates/atualizar.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>

        {% if vagas %}
            <br>
            {% for vaga in vagas %}
                <form action={% url 'core:update' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}     
                    <h4> {{ vaga }} 
                        <input type="hidden" name="id" value={{ vaga.pk }}>        
                        <input  class="btn btn-primary" type="submit" value="Atualizar"/>
                    </h4>   
                    
                </form>
            {% endfor %}
        {% else %}
            <h2> Nenhum contato cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input class="btn btn-secondary" type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

estagios/core/templates/atualizar2.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>

        {% if form %}
        <form action={% url 'core:confirm_update' %} novalidate method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="id" value={{ pk }}>
            <h5>
                {{ form.titulo.label }} : {{ form.titulo }}
            </h5>
            <br>
            <h5>
                {{ form.empresa.label }} : {{ form.empresa }}
            </h5>
            <br>
            <h5>
                {{ form.telefone.label }}: {{ form.telefone }}
            </h5>
            <br><br>
            <center>
                <input class="btn btn-primary" type="submit" value="Atualizar"/>
            </center>
        </form>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <strong>{{ error|escape }}</strong><br>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <br><br>
        {% else %}
            <h2> Nenhuma vaga cadastrada</h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:read' %} novalidate method="GET">
                <input class="btn btn-secondary"  type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

estagios/core/templates/cadastro.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>

        <form action={% url 'core:create' %} novalidate method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h5>
                {{ form.titulo.label }} : {{ form.titulo }}
            </h5>
            <br>
            <h5>
                {{ form.empresa.label }} : {{ form.empresa }}
            </h5>
            <br>
            <h5>
                {{ form.telefone.label }}: {{ form.telefone }}
            </h5>
            <br><br>
            <center>
                <input class="btn btn-primary" type="submit" value="Cadastrar"/>
            </center>
        </form>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <strong>{{ error|escape }}</strong><br>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input class="btn btn-secondary"  type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

estagios/core/templates/detalhes.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>

        {% if vaga %}
            <h4>
                Nome :  {{ vaga.titulo }}
                <br><br>
                Nome :  {{ vaga.empresa }}
                <br><br>
                Telefone : {{ vaga.telefone }}
            </h4>
        <br><br>
        {% else %}
        <h2> Nenhuma vaga cadastrada </h2>     
        {% endif %} 

        <center>
            <form action={% url 'core:read' %} novalidate method="GET">
                <input class="btn btn-secondary"  type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

estagios/core/templates/index.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>
            <form action={% url 'core:create' %} novalidate method="GET">
            <input class="btn btn-primary" type="submit" value="Cadastrar"/>              
        </form>
        <br>
        <form action={% url 'core:read' %} novalidate method="GET">
            <input class="btn btn-primary" type="submit" value="Listar"/>              
        </form>
        <br>
        <form action={% url 'core:update' %} novalidate method="GET">
            <input class="btn btn-primary" type="submit" value="Atualizar"/>              
        </form>
        <br>
        <form action={% url 'core:delete' %} novalidate method="GET">
            <input class="btn btn-primary" type="submit" value="Remover"/>              
        </form>
    </body>

</html>

estagios/core/templates/listar.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>

        {% if vagas %}
            <br>
            {% for vaga in vagas %}
                <form action={% url 'core:read' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}     
                    <h4> {{ vaga }} 
                        <input type="hidden" name="id" value={{ vaga.pk }}>        
                        <input  class="btn btn-primary" type="submit" value="Detalhes"/>
                    </h4>   
                    
                </form>
            {% endfor %}
        {% else %}
            <h2> Nenhuma vaga cadastrada </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input class="btn btn-secondary" type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

estagios/core/templates/remover.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Vagas de Estágio</title>
    </head>
    <body>
        <br>
            <h1>Vagas de Estágio </h1>
            <h2> Cadastro de Vagas de Estágio</h2>
        <br>

        {% if vagas %}
            <br>
            {% for vaga in vagas %}
                <form action={% url 'core:delete' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}     
                    <h4> {{ vaga }} 
                        <input type="hidden" name="id" value={{ vaga.pk }}>        
                        <input  class="btn btn-danger" type="submit" value="Remover"/>
                    </h4>   
                    
                </form>
            {% endfor %}
        {% else %}
            <h2> Nenhum contato cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input class="btn btn-secondary" type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>